In [1]:
import pandas as pd
import numpy as np

In [51]:
df = pd.read_csv("normalized-rna-data.csv", sep=';')

In [52]:
for c in df.columns[1:]:
    df[c] = df[c].str.replace(',','.')
    df[c] = pd.to_numeric(df[c])

In [53]:
for r in range(len(df)):
    df.iloc[r,1:].fillna((df.iloc[r,1:].mean()), inplace=True)

In [54]:
df.Gene = df.Gene.str.split('|')
genes = pd.DataFrame(df["Gene"].to_list(), columns=['Name', 'ID'])

In [55]:
genes

            Name         ID
0              ?  100133144
1              ?  100134869
2              ?      10357
3              ?      10431
4              ?     155060
...          ...        ...
17714     ZYG11B      79699
17715        ZYX       7791
17716      ZZEF1      23140
17717       ZZZ3      26009
17718  psiTPTE22     387590

[17719 rows x 2 columns]

In [56]:
df.drop(['Gene'], axis=1, inplace=True)

In [64]:
df_clean = pd.concat([genes, df], axis=1)
df_clean

,Name,ID,TCGA-4P-AA8J,TCGA-BA-4074,TCGA-BA-4075,TCGA-BA-4076,TCGA-BA-4077,TCGA-BA-4078,TCGA-BA-5149,TCGA-BA-5151,...,TCGA-UF-A7JJ,TCGA-UF-A7JK,TCGA-UF-A7JO,TCGA-UF-A7JS,TCGA-UF-A7JT,TCGA-UF-A7JV,TCGA-UP-A6WW,TCGA-WA-A7GZ,TCGA-WA-A7GZ.1,TCGA-WA-A7H4
0,?,100133144,-2.668367,-0.902774,-0.875868,-0.788130,-0.720443,0.305505,-1.884686,-2.273196,...,-1.487508,0.784834,-1.195505,-2.153869,-2.552769,-2.570372,-0.957308,1.103520,1.055458,0.110682
1,?,100134869,-0.794596,-1.020686,-2.464098,-2.221278,-0.817997,-0.380211,-1.300005,-2.467344,...,-0.272792,0.844650,-1.583013,-2.747920,-3.398868,-0.710990,-0.290401,1.118641,0.730860,0.065397
2,?,10357,2.411792,3.752946,3.888404,3.634904,3.915315,3.313590,3.563117,2.727658,...,1.744007,2.406473,3.157449,-0.420827,2.519974,2.545822,2.312506,1.767151,2.989047,2.724889
3,?,10431,5.945483,6.270801,5.988357,5.749688,5.322637,5.071589,5.728863,6.196538,...,4.973021,5.648660,5.790883,5.388906,6.208256,5.519225,5.984255,5.102151,4.833012,5.228947
4,?,155060,3.523286,0.672797,1.733573,2.330802,1.187771,3.408542,1.881185,1.889117,...,2.299783,1.950906,3.446527,1.640209,3.734540,4.292657,2.999944,3.518798,3.219246,3.645937
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17714,ZYG11B,79699,4.176802,5.011630,4.375613,5.011237,5.175596,5.306228,4.525589,5.531478,...,5.019014,4.841961,4.234894,2.858784,3.977971,4.620639,4.268517,6.704048,4.644218,5.545347
17715,ZYX,7791,8.967494,6.655512,7.978120,6.898629,8.556480,7.625407,7.961349,8.105545,...,7.677835,7.804717,7.561616,7.363458,8.530718,8.627586,7.940130,5.879767,7.323343,8.053697
17716,ZZEF1,23140,5.248309,3.375093,3.639632,4.907054,5.161124,6.302415,5.395046,6.357876,...,5.573614,6.203574,5.777273,4.068463,5.406358,4.919382,5.680214,6.206898,6.381286,6.527878
17717,ZZZ3,26009,3.952576,5.446325,5.381988,5.477708,5.021896,6.053211,5.619469,5.054428,...,4.372185,4.341782,4.535543,2.966107,4.379730,4.661430,4.479786,4.537601,5.016662,5.876392
17718,psiTPTE22,387590,-0.242836,-0.127967,-1.373839,-1.172729,-1.467482,0.446395,-2.301554,-1.195793,...,-1.141041,-1.545836,-1.820596,-1.313832,-1.653056,-0.666252,-2.106968,4.258512,3.645529,1.866726

In [65]:
df_clean.to_csv("expression_clean.csv", index=False)

In [70]:
df_patients = pd.read_csv("ITH-H_N_Judith.csv", sep=';')

In [101]:
select_cols = ['Name', 'ID'] + df_patients.PATIENT_ID.values.tolist()

In [102]:
df_clean_sub = df_clean.reindex(columns = select_cols)

In [103]:
df_clean_sub

,Name,ID,TCGA-4P-AA8J,TCGA-BA-4074,TCGA-BA-4076,TCGA-BA-4078,TCGA-BA-5149,TCGA-BA-5151,TCGA-BA-5152,TCGA-BA-5153,...,TCGA-UF-A7JH,TCGA-UF-A7JJ,TCGA-UF-A7JK,TCGA-UF-A7JO,TCGA-UF-A7JS,TCGA-UF-A7JT,TCGA-UF-A7JV,TCGA-UP-A6WW,TCGA-WA-A7GZ,TCGA-WA-A7H4
0,?,100133144,-2.668367,-0.902774,-0.788130,0.305505,-1.884686,-2.273196,-1.028562,-2.359103,...,-0.509501,-1.487508,0.784834,-1.195505,-2.153869,-2.552769,-2.570372,-0.957308,1.103520,0.110682
1,?,100134869,-0.794596,-1.020686,-2.221278,-0.380211,-1.300005,-2.467344,-2.103687,-1.200386,...,-1.010059,-0.272792,0.844650,-1.583013,-2.747920,-3.398868,-0.710990,-0.290401,1.118641,0.065397
2,?,10357,2.411792,3.752946,3.634904,3.313590,3.563117,2.727658,2.735800,3.036732,...,2.429561,1.744007,2.406473,3.157449,-0.420827,2.519974,2.545822,2.312506,1.767151,2.724889
3,?,10431,5.945483,6.270801,5.749688,5.071589,5.728863,6.196538,5.694105,5.245816,...,5.358525,4.973021,5.648660,5.790883,5.388906,6.208256,5.519225,5.984255,5.102151,5.228947
4,?,155060,3.523286,0.672797,2.330802,3.408542,1.881185,1.889117,-0.802738,2.312371,...,3.879251,2.299783,1.950906,3.446527,1.640209,3.734540,4.292657,2.999944,3.518798,3.645937
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17714,ZYG11B,79699,4.176802,5.011630,5.011237,5.306228,4.525589,5.531478,4.455235,5.321958,...,3.944405,5.019014,4.841961,4.234894,2.858784,3.977971,4.620639,4.268517,6.704048,5.545347
17715,ZYX,7791,8.967494,6.655512,6.898629,7.625407,7.961349,8.105545,8.007809,8.088375,...,7.928419,7.677835,7.804717,7.561616,7.363458,8.530718,8.627586,7.940130,5.879767,8.053697
17716,ZZEF1,23140,5.248309,3.375093,4.907054,6.302415,5.395046,6.357876,5.312153,6.707029,...,5.267850,5.573614,6.203574,5.777273,4.068463,5.406358,4.919382,5.680214,6.206898,6.527878
17717,ZZZ3,26009,3.952576,5.446325,5.477708,6.053211,5.619469,5.054428,4.255414,5.509953,...,4.497807,4.372185,4.341782,4.535543,2.966107,4.379730,4.661430,4.479786,4.537601,5.876392
17718,psiTPTE22,387590,-0.242836,-0.127967,-1.172729,0.446395,-2.301554,-1.195793,-2.740848,0.006735,...,3.150084,-1.141041,-1.545836,-1.820596,-1.313832,-1.653056,-0.666252,-2.106968,4.258512,1.866726

In [174]:
df_clean_sub.to_csv("expression_subset.csv", index=False)

In [163]:
df_p_t = df_patients.loc[:, ['PATIENT_ID', 'binary_vital_status', 'survival_days']].T
# need to replace , and .
cols_new = df_p_t.loc['PATIENT_ID', :].values
df_p_t.columns = cols_new
df_p_t = df_p_t.reindex(columns = select_cols[2:])

In [167]:
df_p_t.loc['survival_days', :] = df_p_t.loc['survival_days', :].str.replace(',','.')
df_p_t

,TCGA-4P-AA8J,TCGA-BA-4074,TCGA-BA-4076,TCGA-BA-4078,TCGA-BA-5149,TCGA-BA-5151,TCGA-BA-5152,TCGA-BA-5153,TCGA-BA-5555,TCGA-BA-5556,...,TCGA-UF-A7JH,TCGA-UF-A7JJ,TCGA-UF-A7JK,TCGA-UF-A7JO,TCGA-UF-A7JS,TCGA-UF-A7JT,TCGA-UF-A7JV,TCGA-UP-A6WW,TCGA-WA-A7GZ,TCGA-WA-A7H4
PATIENT_ID,TCGA-4P-AA8J,TCGA-BA-4074,TCGA-BA-4076,TCGA-BA-4078,TCGA-BA-5149,TCGA-BA-5151,TCGA-BA-5152,TCGA-BA-5153,TCGA-BA-5555,TCGA-BA-5556,...,TCGA-UF-A7JH,TCGA-UF-A7JJ,TCGA-UF-A7JK,TCGA-UF-A7JO,TCGA-UF-A7JS,TCGA-UF-A7JT,TCGA-UF-A7JV,TCGA-UP-A6WW,TCGA-WA-A7GZ,TCGA-WA-A7H4
binary_vital_status,0,1,1,1,1,0,0,1,0,0,...,0,0,1,1,1,1,1,0,1,0
survival_days,102.175,462.99,415.715,276.635,807.64,723.46,1290.455,1765.34,520.94,726.51,...,897.615,550.22,424.865,632.265,681.37,994.91,90.28,519.11,626.165,443.775

In [150]:
df_region = pd.read_csv("cancer_region.csv", sep=';', names=['region', 'patient_id'], skiprows=1)

In [151]:
df_region.patient_id = df_region.patient_id.str.upper()

In [152]:
df_region = df_region.T
df_region

,0,1,2,3,4,5,6,7,8,9,...,518,519,520,521,522,523,524,525,526,527
region,oral tongue,base of tongue,oral tongue,tonsil,base of tongue,base of tongue,oropharynx,oral cavity,larynx,larynx,...,larynx,larynx,floor of mouth,oral tongue,floor of mouth,oral tongue,floor of mouth,oral tongue,larynx,floor of mouth
patient_id,TCGA-BA-4075,TCGA-BA-4077,TCGA-BA-5557,TCGA-BA-5559,TCGA-BA-6871,TCGA-BA-A4IG,TCGA-BA-A4II,TCGA-BB-A5HU,TCGA-CN-4727,TCGA-CN-6021,...,TCGA-UF-A7JJ,TCGA-UF-A7JK,TCGA-UF-A7JO,TCGA-UF-A7JS,TCGA-UF-A7JT,TCGA-UP-A6WW,TCGA-WA-A7GZ,TCGA-WA-A7H4,TCGA-KU-A66S,TCGA-KU-A66T

In [154]:
new_cols = df_region.loc['patient_id', :].values

In [156]:
df_region.columns = new_cols

In [158]:
df_region = df_region.reindex(columns = select_cols[2:])

In [159]:
df_region

,TCGA-4P-AA8J,TCGA-BA-4074,TCGA-BA-4076,TCGA-BA-4078,TCGA-BA-5149,TCGA-BA-5151,TCGA-BA-5152,TCGA-BA-5153,TCGA-BA-5555,TCGA-BA-5556,...,TCGA-UF-A7JH,TCGA-UF-A7JJ,TCGA-UF-A7JK,TCGA-UF-A7JO,TCGA-UF-A7JS,TCGA-UF-A7JT,TCGA-UF-A7JV,TCGA-UP-A6WW,TCGA-WA-A7GZ,TCGA-WA-A7H4
region,oral tongue,oral tongue,larynx,larynx,floor of mouth,buccal mucosa,alveolar ridge,tonsil,larynx,floor of mouth,...,larynx,larynx,larynx,floor of mouth,oral tongue,floor of mouth,hypopharynx,oral tongue,floor of mouth,oral tongue
patient_id,TCGA-4P-AA8J,TCGA-BA-4074,TCGA-BA-4076,TCGA-BA-4078,TCGA-BA-5149,TCGA-BA-5151,TCGA-BA-5152,TCGA-BA-5153,TCGA-BA-5555,TCGA-BA-5556,...,TCGA-UF-A7JH,TCGA-UF-A7JJ,TCGA-UF-A7JK,TCGA-UF-A7JO,TCGA-UF-A7JS,TCGA-UF-A7JT,TCGA-UF-A7JV,TCGA-UP-A6WW,TCGA-WA-A7GZ,TCGA-WA-A7H4

In [172]:
pd_surv = pd.concat([df_p_t, df_region]).drop('patient_id', inplace=False)

In [176]:
pd_surv

,TCGA-4P-AA8J,TCGA-BA-4074,TCGA-BA-4076,TCGA-BA-4078,TCGA-BA-5149,TCGA-BA-5151,TCGA-BA-5152,TCGA-BA-5153,TCGA-BA-5555,TCGA-BA-5556,...,TCGA-UF-A7JH,TCGA-UF-A7JJ,TCGA-UF-A7JK,TCGA-UF-A7JO,TCGA-UF-A7JS,TCGA-UF-A7JT,TCGA-UF-A7JV,TCGA-UP-A6WW,TCGA-WA-A7GZ,TCGA-WA-A7H4
PATIENT_ID,TCGA-4P-AA8J,TCGA-BA-4074,TCGA-BA-4076,TCGA-BA-4078,TCGA-BA-5149,TCGA-BA-5151,TCGA-BA-5152,TCGA-BA-5153,TCGA-BA-5555,TCGA-BA-5556,...,TCGA-UF-A7JH,TCGA-UF-A7JJ,TCGA-UF-A7JK,TCGA-UF-A7JO,TCGA-UF-A7JS,TCGA-UF-A7JT,TCGA-UF-A7JV,TCGA-UP-A6WW,TCGA-WA-A7GZ,TCGA-WA-A7H4
binary_vital_status,0,1,1,1,1,0,0,1,0,0,...,0,0,1,1,1,1,1,0,1,0
survival_days,102.175,462.99,415.715,276.635,807.64,723.46,1290.455,1765.34,520.94,726.51,...,897.615,550.22,424.865,632.265,681.37,994.91,90.28,519.11,626.165,443.775
region,oral tongue,oral tongue,larynx,larynx,floor of mouth,buccal mucosa,alveolar ridge,tonsil,larynx,floor of mouth,...,larynx,larynx,larynx,floor of mouth,oral tongue,floor of mouth,hypopharynx,oral tongue,floor of mouth,oral tongue

In [178]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(pd_surv.loc['region', :])
pd_surv.loc['region_class', :] = le.transform(pd_surv.loc['region', :])
pd_surv

,TCGA-4P-AA8J,TCGA-BA-4074,TCGA-BA-4076,TCGA-BA-4078,TCGA-BA-5149,TCGA-BA-5151,TCGA-BA-5152,TCGA-BA-5153,TCGA-BA-5555,TCGA-BA-5556,...,TCGA-UF-A7JH,TCGA-UF-A7JJ,TCGA-UF-A7JK,TCGA-UF-A7JO,TCGA-UF-A7JS,TCGA-UF-A7JT,TCGA-UF-A7JV,TCGA-UP-A6WW,TCGA-WA-A7GZ,TCGA-WA-A7H4
PATIENT_ID,TCGA-4P-AA8J,TCGA-BA-4074,TCGA-BA-4076,TCGA-BA-4078,TCGA-BA-5149,TCGA-BA-5151,TCGA-BA-5152,TCGA-BA-5153,TCGA-BA-5555,TCGA-BA-5556,...,TCGA-UF-A7JH,TCGA-UF-A7JJ,TCGA-UF-A7JK,TCGA-UF-A7JO,TCGA-UF-A7JS,TCGA-UF-A7JT,TCGA-UF-A7JV,TCGA-UP-A6WW,TCGA-WA-A7GZ,TCGA-WA-A7H4
binary_vital_status,0,1,1,1,1,0,0,1,0,0,...,0,0,1,1,1,1,1,0,1,0
survival_days,102.175,462.99,415.715,276.635,807.64,723.46,1290.455,1765.34,520.94,726.51,...,897.615,550.22,424.865,632.265,681.37,994.91,90.28,519.11,626.165,443.775
region,oral tongue,oral tongue,larynx,larynx,floor of mouth,buccal mucosa,alveolar ridge,tonsil,larynx,floor of mouth,...,larynx,larynx,larynx,floor of mouth,oral tongue,floor of mouth,hypopharynx,oral tongue,floor of mouth,oral tongue
region_class,9,9,6,6,3,2,0,11,6,3,...,6,6,6,3,9,3,5,9,3,9

In [181]:
le.classes_ # 11

array(['alveolar ridge', 'base of tongue', 'buccal mucosa',
       'floor of mouth', 'hard palate', 'hypopharynx', 'larynx', 'lip',
       'oral cavity', 'oral tongue', 'oropharynx', 'tonsil'], dtype=object)

In [179]:
pd_surv.to_csv("surv_subset.csv", index=False)

In [2]:
df = pd.read_csv('surv_subset.csv')

In [4]:
df # 1= vital, 2 = years

,TCGA-4P-AA8J,TCGA-BA-4074,TCGA-BA-4076,TCGA-BA-4078,TCGA-BA-5149,TCGA-BA-5151,TCGA-BA-5152,TCGA-BA-5153,TCGA-BA-5555,TCGA-BA-5556,...,TCGA-UF-A7JH,TCGA-UF-A7JJ,TCGA-UF-A7JK,TCGA-UF-A7JO,TCGA-UF-A7JS,TCGA-UF-A7JT,TCGA-UF-A7JV,TCGA-UP-A6WW,TCGA-WA-A7GZ,TCGA-WA-A7H4
0,TCGA-4P-AA8J,TCGA-BA-4074,TCGA-BA-4076,TCGA-BA-4078,TCGA-BA-5149,TCGA-BA-5151,TCGA-BA-5152,TCGA-BA-5153,TCGA-BA-5555,TCGA-BA-5556,...,TCGA-UF-A7JH,TCGA-UF-A7JJ,TCGA-UF-A7JK,TCGA-UF-A7JO,TCGA-UF-A7JS,TCGA-UF-A7JT,TCGA-UF-A7JV,TCGA-UP-A6WW,TCGA-WA-A7GZ,TCGA-WA-A7H4
1,0,1,1,1,1,0,0,1,0,0,...,0,0,1,1,1,1,1,0,1,0
2,102.175,462.99,415.715,276.635,807.64,723.46,1290.455,1765.34,520.94,726.51,...,897.615,550.22,424.865,632.265,681.37,994.91,90.28,519.11,626.165,443.775
3,oral tongue,oral tongue,larynx,larynx,floor of mouth,buccal mucosa,alveolar ridge,tonsil,larynx,floor of mouth,...,larynx,larynx,larynx,floor of mouth,oral tongue,floor of mouth,hypopharynx,oral tongue,floor of mouth,oral tongue
4,9,9,6,6,3,2,0,11,6,3,...,6,6,6,3,9,3,5,9,3,9

In [13]:
hpv_pos = pd.read_csv("hpv_pos.csv", sep=';')
hpv_neg = pd.read_csv("hpv_neg.csv", sep=';')

In [19]:
clin_full = pd.read_csv("full_clin.csv", sep=';')#, names= ['patient.margin_status']) # patient.margin_status # patient.drugs.drug.therapy_types.therapy_type, # patient.alcohol_history_documented # patient.neoplasm_histologic_grade

/Users/sina/opt/anaconda3/envs/main/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (7,15,16,17,22,31,32,36,38,39,44,54,55,59,61,62,67,68,72,73,76,77,78,79,82,83,85,86,91,92,95,96,97,100,101,102,105,106,108,109,114,115,119,120,123,124,125,126,128,129,131,132,137,138,142,143,146,147,148,151,152,154,155,160,161,165,166,169,170,171,175,177,178,183,184,188,189,192,193,194,198,200,201,206,207,216,217,221,223,224,229,239,240,244,248,256,257,258,261,265,266,269,272,273,274,275,285,289,291,292,293,294,295,298,299,300,301,302,304,310,311,312,316,317,318,320,321,329,330,331,332,333,335,336,337,338,339,342,343,344,345,346,347,348,349,350,351,354,355,356,357,358,360,361,362,364,365,373,374,375,376,377,379,381,382,383,386,387,388,389,390,391,392,393,394,395,398,400,401,402,404,405,410,411,412,413,414,416,417,420,421,422,423,424,425,426,427,428,429,432,434,435,436,438,439,440,441,457,458,459,460,461,464,465,466,467,468,491,495,496,545,549,550,553,554,555,560,563,564,565,567,568,569,571,572,573,578,581,582,583,585,586,587,589,590,591,600,601,603,605,607,608,609,618,619,621,623,625,626,627,636,637,639,641,653,657,658,692,696,697,701,716,718,719,721,724,725,728,730,733,734,735,751,759,767,768,769,775,776,779,781,784,785,790,791,792,793,795,796,797,798,799,805,821,824,825,828,830,833,834,835,837,840,841,844,846,849,850,851,853,856,857,860,862,865,866,867,869,872,873,876,878,881,882,883,885,928,929,931,944,946,947,948,949,962,976,987,989,996,999,1000,1003,1005,1009,1010,1012,1015,1016,1019,1021,1024,1025,1026,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1042,1043,1044,1050,1051,1054,1056,1059,1060,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1077,1085,1097,1100,1101,1104,1106,1109,1110,1111,1113,1116,1117,1120,1122,1126,1127,1129,1132,1133,1136,1138,1142,1143,1150,1162,1168,1170,1171,1214,1232,1233,1236,1238,1240,1261,1264,1265,1268,1270,1273,1274,1275,1277,1293,1313,1314,1317,1319,1322,1323,1348,1356,1357,1358,1364,1365,1368,1370,1374,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1391,1394,1410,1426,1429,1430,1433,1435,1438,1439,1440,1442,1445,1446,1449,1451,1454,1455,1456,1461,1462,1465,1467,1470,1471,1472,1474,1477,1478,1481,1483,1487,1488,1493,1494,1497,1499,1502,1503,1504,1542,1547,1548,1549,1550,1563,1595,1602,1603,1606,1608,1609,1610,1613,1614,1615,1616,1617,1618,1620,1621,1622,1624,1625,1626,1628,1629,1630,1631,1634,1636,1637,1638,1641,1642,1643,1644,1645,1646,1647,1648,1649,1650,1652,1653,1654,1656,1657,1664,1665,1666,1667,1669,1671,1676,1677,1678,1681,1684,1685,1686,1690,1693,1696,1699,1700,1701,1702,1704,1705,1706,1708,1713,1714,1725,1731,1736,1741,1750,1751) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [33]:
#clin_full.columns.values.tolist()

In [44]:
clin_sub = clin_full.loc[:,['patient.bcr_patient_barcode+J2+J2+J2+J2', 'patient.alcohol_history_documented', 'patient.drugs.drug.therapy_types.therapy_type', 'patient.age_at_initial_pathologic_diagnosis', 'patient.amount_of_alcohol_consumption_per_day', 'patient.margin_status', 'patient.neoplasm_histologic_grade']]

In [36]:
hpv_neg

,patient.bcr_patient_barcode+J2+J2+J2+J2,patient.hpv_test_results.hpv_test_result.hpv_status,patient.stage_event.tnm_categories.pathologic_categories.pathologic_m,patient.stage_event.tnm_categories.pathologic_categories.pathologic_n,patient.stage_event.tnm_categories.pathologic_categories.pathologic_t,patient.stage_event.pathologic_stage,patient.anatomic_neoplasm_subdivision
0,tcga-ba-a6dj,negative,m0,n2c,t4a,stage iva,alveolar ridge
1,tcga-cn-6011,negative,NaN,n0,t4a,stage iva,alveolar ridge
2,tcga-cn-6013,negative,NaN,n2b,t4a,stage iva,alveolar ridge
3,tcga-cn-a49a,negative,mx,n0,t4b,stage ivb,alveolar ridge
4,tcga-cq-5326,negative,NaN,n2c,t4a,stage iva,alveolar ridge
...,...,...,...,...,...,...,...
422,tcga-cr-7383,negative,m0,n0,t1,stage i,tonsil
423,tcga-cr-7404,negative,NaN,nx,tx,NaN,tonsil
424,tcga-mt-a51w,negative,m0,n0,t1,stage i,tonsil
425,tcga-p3-a5q6,negative,mx,n2b,t4a,stage iva,tonsil
426,tcga-p3-a6sx,negative,mx,n1,t2,stage iii,tonsil

In [47]:
hpv = pd.concat([hpv_pos, hpv_neg]) #axis=1
hpv_sub = hpv.loc[:, ['patient.bcr_patient_barcode+J2+J2+J2+J2', 'patient.hpv_test_results.hpv_test_result.hpv_status' ]]

In [42]:
#hpv_sub.columns = ['ID', 'HPV_status'] # FINAL

In [53]:
clin_final = pd.merge(clin_sub, hpv_sub, on='patient.bcr_patient_barcode+J2+J2+J2+J2')

In [54]:
clin_final['patient.bcr_patient_barcode+J2+J2+J2+J2'] = clin_final['patient.bcr_patient_barcode+J2+J2+J2+J2'].str.upper()

In [58]:
clin_final['patient.bcr_patient_barcode+J2+J2+J2+J2'] = clin_final['patient.bcr_patient_barcode+J2+J2+J2+J2'].str.replace('-','.')

In [59]:
clin_final

,patient.bcr_patient_barcode+J2+J2+J2+J2,patient.alcohol_history_documented,patient.drugs.drug.therapy_types.therapy_type,patient.age_at_initial_pathologic_diagnosis,patient.amount_of_alcohol_consumption_per_day,patient.margin_status,patient.neoplasm_histologic_grade,patient.hpv_test_results.hpv_test_result.hpv_status
0,TCGA.BA.4075,yes,chemotherapy,49.0,5,positive,g2,negative
1,TCGA.BA.4077,yes,chemotherapy,45.0,0,negative,g2,positive
2,TCGA.BA.5557,yes,chemotherapy,41.0,0,negative,g2,negative
3,TCGA.BA.5559,yes,NaN,71.0,0,positive,g3,positive
4,TCGA.BA.6871,yes,NaN,75.0,NaN,NaN,g2,negative
...,...,...,...,...,...,...,...,...
521,TCGA.UP.A6WW,yes,NaN,58.0,3.0,negative,g2,positive
522,TCGA.WA.A7GZ,NaN,NaN,58.0,NaN,negative,g2,negative
523,TCGA.WA.A7H4,NaN,NaN,69.0,NaN,negative,g3,negative
524,TCGA.KU.A66S,no,NaN,69.0,NaN,positive,g2,negative
525,TCGA.KU.A66T,no,NaN,53.0,NaN,negative,g2,negative

In [60]:
clin_final.to_csv("clinical_indicators.csv", index=False)